-- Script para crear la tabla de accidentes en MySQL

CREATE DATABASE IF NOT EXISTS accidents_db;
USE accidents_db;

CREATE TABLE IF NOT EXISTS accidentes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_SINIESTRO DATETIME,
    HORA_SINIESTRO INT NOT NULL,
    CLASE_SINIESTRO INT NOT NULL,
    CANTIDAD_DE_VEHICULOS_DAÑADOS INT NOT NULL,
    DISTRITO INT NOT NULL,
    ZONA INT NOT NULL,
    TIPO_DE_VIA INT NOT NULL,
    RED_VIAL INT NOT NULL,
    EXISTE_CICLOVIA INT NOT NULL,
    COORDENADAS_LATITUD FLOAT,
    COORDENADAS_LONGITUD FLOAT,
    CONDICION_CLIMATICA INT NOT NULL,
    ZONIFICACION INT NOT NULL,
    CARACTERISTICAS_DE_VIA INT NOT NULL,
    PERFIL_LONGITUDINAL_VIA INT NOT NULL,
    SUPERFICIE_DE_CALZADA INT NOT NULL,
    senalizacion INT NOT NULL,
    DIA_DE_LA_SEMANA INT NOT NULL,
    MES INT NOT NULL,
    PERIODO_DEL_DIA INT NOT NULL,
    Feriado INT NOT NULL,
    ACCIDENTE INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_distrito (DISTRITO),
    INDEX idx_fecha (FECHA_SINIESTRO)
);

-- Ejemplo de inserción de datos (opcional)
-- INSERT INTO accidentes (FECHA_SINIESTRO, HORA_SINIESTRO, CLASE_SINIESTRO, ...) VALUES ('2023-01-01 00:00:00', 12, 1, ...);