# Generated by Django 5.2.1 on 2025-06-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HORA_SINIESTRO', models.IntegerField()),
                ('CLASE_SINIESTRO', models.IntegerField()),
                ('CANTIDAD_DE_VEHICULOS_DANADOS', models.IntegerField()),
                ('DISTRITO', models.IntegerField()),
                ('ZONA', models.IntegerField()),
                ('TIPO_DE_VIA', models.IntegerField()),
                ('RED_VIAL', models.IntegerField()),
                ('EXISTE_CICLOVIA', models.IntegerField()),
                ('CONDICION_CLIMATICA', models.IntegerField()),
                ('ZONIFICACION', models.IntegerField()),
                ('CARACTERISTICAS_DE_VIA', models.IntegerField()),
                ('PERFIL_LONGITUDINAL_VIA', models.IntegerField()),
                ('SUPERFICIE_DE_CALZADA', models.IntegerField()),
                ('SENALIZACION', models.IntegerField()),
                ('DIA_DE_LA_SEMANA', models.IntegerField()),
                ('MES', models.IntegerField()),
                ('PERIODO_DEL_DIA', models.IntegerField()),
                ('FERIADO', models.IntegerField()),
                ('ACCIDENTE', models.IntegerField()),
                ('FECHA_SINIESTRO', models.DateField()),
                ('FECHA_INGRESO', models.DateField()),
            ],
        ),
    ]
