# Generated by Django 5.2 on 2025-06-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='siniestro',
        #     old_name='CANTIDAD_DE_VEHICULOS_DANADOS',
        #     new_name='CANTIDAD_DE_VEHICULOS_DANADOS',
        # ),
        migrations.AlterModelTable(
            name='siniestro',
            table='projects_siniestro',
        ),
    ]
